id: I439E78F7
ocr_import_info:
  bdrc_scan_id: W00EGS1016951
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0001
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-03-06 11:10:27.115020
last_modified: 2022-08-25 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016951
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016951
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་ཊཱིཀ་རིན་ཆེན་འཕྲེང་བ།
  languages:
  - bo
  author: དགེ་འདུན་གྲུབ་པ།
bases:
  I01JW173:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW173
      total_pages: 600
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I01JW173.txt
    order: 1
  I01JW174:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW174
      total_pages: 468
      volume_number: 2
      volume_pages_bdrc_intro: 2
    base_file: I01JW174.txt
    order: 2
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
